version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
    steps:
      - checkout
      - restore_cache:
          key: v1-bundle-{{ checksum "library-kanagawa_yamato.gemspec" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: v1-bundle-{{ checksum "library-kanagawa_yamato.gemspec" }}
          paths:
            - vendor/bundle
      - run:
          name: Rspec
          command: bundle exec rspec --format progress
